[package]
name = "snake"
version = "0.1.0"
authors = ["Robert Szeker"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
max-7219-led-matrix-util = "0.1.4"
termion = "1.5.6"
rand= "0.8.3"